/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface JogoDataDto {
  classificacaoEtaria?: string;
  dataLancamento?: string;
  desenvolvedora?: string;
  genero?: string;
  multiplayer?: boolean;
  plataforma?: string;
  titulo?: string;
}
