/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { create } from '../fn/jogo-controller/create';
import { Create$Params } from '../fn/jogo-controller/create';
import { delete$ } from '../fn/jogo-controller/delete';
import { Delete$Params } from '../fn/jogo-controller/delete';
import { getById } from '../fn/jogo-controller/get-by-id';
import { GetById$Params } from '../fn/jogo-controller/get-by-id';
import { Jogo } from '../models/jogo';
import { listAll } from '../fn/jogo-controller/list-all';
import { ListAll$Params } from '../fn/jogo-controller/list-all';
import { listByGenero } from '../fn/jogo-controller/list-by-genero';
import { ListByGenero$Params } from '../fn/jogo-controller/list-by-genero';
import { update } from '../fn/jogo-controller/update';
import { Update$Params } from '../fn/jogo-controller/update';

@Injectable({ providedIn: 'root' })
export class JogoControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getById()` */
  static readonly GetByIdPath = '/jogo/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById$Response(params: GetById$Params, context?: HttpContext): Observable<StrictHttpResponse<Jogo>> {
    return getById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getById(params: GetById$Params, context?: HttpContext): Observable<Jogo> {
    return this.getById$Response(params, context).pipe(
      map((r: StrictHttpResponse<Jogo>): Jogo => r.body)
    );
  }

  /** Path part for operation `update()` */
  static readonly UpdatePath = '/jogo/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `update()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update$Response(params: Update$Params, context?: HttpContext): Observable<StrictHttpResponse<Jogo>> {
    return update(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `update$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  update(params: Update$Params, context?: HttpContext): Observable<Jogo> {
    return this.update$Response(params, context).pipe(
      map((r: StrictHttpResponse<Jogo>): Jogo => r.body)
    );
  }

  /** Path part for operation `delete()` */
  static readonly DeletePath = '/jogo/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delete()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete$Response(params: Delete$Params, context?: HttpContext): Observable<StrictHttpResponse<Jogo>> {
    return delete$(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delete(params: Delete$Params, context?: HttpContext): Observable<Jogo> {
    return this.delete$Response(params, context).pipe(
      map((r: StrictHttpResponse<Jogo>): Jogo => r.body)
    );
  }

  /** Path part for operation `listAll()` */
  static readonly ListAllPath = '/jogo';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAll$Response(params?: ListAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Jogo>>> {
    return listAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listAll(params?: ListAll$Params, context?: HttpContext): Observable<Array<Jogo>> {
    return this.listAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Jogo>>): Array<Jogo> => r.body)
    );
  }

  /** Path part for operation `create()` */
  static readonly CreatePath = '/jogo';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `create()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create$Response(params: Create$Params, context?: HttpContext): Observable<StrictHttpResponse<Jogo>> {
    return create(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `create$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  create(params: Create$Params, context?: HttpContext): Observable<Jogo> {
    return this.create$Response(params, context).pipe(
      map((r: StrictHttpResponse<Jogo>): Jogo => r.body)
    );
  }

  /** Path part for operation `listByGenero()` */
  static readonly ListByGeneroPath = '/jogo/genero/{genero}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listByGenero()` instead.
   *
   * This method doesn't expect any request body.
   */
  listByGenero$Response(params: ListByGenero$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Jogo>>> {
    return listByGenero(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listByGenero$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listByGenero(params: ListByGenero$Params, context?: HttpContext): Observable<Array<Jogo>> {
    return this.listByGenero$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Jogo>>): Array<Jogo> => r.body)
    );
  }

}
