/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Jogo } from '../../models/jogo';

export interface ListByGenero$Params {
  genero: string;
}

export function listByGenero(http: HttpClient, rootUrl: string, params: ListByGenero$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Jogo>>> {
  const rb = new RequestBuilder(rootUrl, listByGenero.PATH, 'get');
  if (params) {
    rb.path('genero', params.genero, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Jogo>>;
    })
  );
}

listByGenero.PATH = '/jogo/genero/{genero}';
